export const LOGOUT = 'LOGOUT'
export const FETCH_COMPANY_INFO = 'FETCH_COMPANY_INFO'
export const DISPLAY_COMPANY_INFO = 'DISPLAY_COMPANY_INFO'
export const DISPLAY_COMPANY_INFO_FAILED = 'DISPLAY_COMPANY_INFO_FAILED'
